### ISSUE TITLE
[BUG] The generate endpoint is throwing 500 error

### ISSUE THREAD

**Issue by kelvinrferreira** [asyncapi/playground#11]
**Describe the bug**
While trying to generate a new specification at https://playground.asyncapi.io/ URL the site doesn't respond and log on the console a 500 error `Unexpected error`

**To Reproduce**
1. Access the default api examples
2. Try to change some label
3. Everything works
4. Force an error on some tag or paste a new completely different interface
5. The page doesn't update and the error is no shown.

**Expected behavior**
The page should update with the new information or with the error properly described on the page

**Additional context**
Looks like nothing is happening at the first look but its throwing error on the `generate` endpoint on console
```
Request URL: https://playground.asyncapi.io/html/generate
Request Method: POST
Status Code: 500 
Remote Address: 138.197.228.203:443
Referrer Policy: no-referrer-when-downgrade
```

**Comment by fmvilas** [comment]
Thanks for reporting, @kelvinrferreira. Checking.

**Comment by fmvilas** [comment]
It should be fixed now. Can you confirm? Thanks a lot!

**Comment by kelvinrferreira** [comment]
Thanks for following up @fmvilas .

I've tested and now it's showing the syntax errors correctly! But now is throwing some errors about the version.

Error message:
```
Version 2.0.0-rc1 is not supported. Only the latest release candidate version is supported until 2.0.0 is released.
```

And when I change to 2.0 it throws:
```
AsyncAPI version is missing or unsupported: 2.0.0.
```

🤔 I'm wondering now if the problem is on my interface...

**Comment by fmvilas** [comment]
Yes, latest supported version is 2.0.0-rc2. Since 2.0.0-rc1 and 2.0.0-rc2 are release candidates, we don't support each of them but only the latest one. The converter CLI may help in you: https://github.com/asyncapi/converter.

Please, be aware that soon I'll release final version 2.0.0. It's highly probable that 2.0.0 and 2.0.0-rc2 are the same, at least in syntax, so they should be compatible with each other. That said, you would have to change `2.0.0-rc2` to `2.0.0` when it's released.

**Comment by kelvinrferreira** [comment]
Oh, that's good news.

I'll do this. Thank you!
