### ISSUE TITLE
Error due to signature too long

### ISSUE THREAD

**Issue by DanielFran** [asyncapi/playground#19]
#### Describe the bug
Using a description with at least 2000 lines give an error in playground.

#### How to Reproduce
Just needed to use a description with at least 2000 lines
![image](https://user-images.githubusercontent.com/3706415/79875987-5c250900-83e2-11ea-95f5-caf40ed6dd94.png)

#### Expected behavior
Playground should handle long description schema

**Comment by DanielFran** [comment]
Same issue using AsyncAPIhub:
![image](https://user-images.githubusercontent.com/3706415/81115791-32103280-8f1c-11ea-9829-4214741e0458.png)

**Comment by DanielFran** [comment]
Closing due to no feedback 😞

**Comment by derberg** [comment]
@DanielFran so sorry for not getting back to you, this issue was lost in the between other topics 😞 
we are not making to many changes in the playground because of https://github.com/asyncapi/playground/issues/20#issuecomment-646463443. Can you check if you have the same issue here https://hub.asyncapi.io/ ?
